spring:
  # profile:
  #   active: dev
  application:
    name: AUTH-SERVICE
  cloud:
    config:
      name: auth-service
      uri: http://configuration-server:8888
  config:      
   import: "optional:configserver:"
